In [1]:
from data_loader import PreLoadedReps
from transformers import BertTokenizer, AutoTokenizer, AutoModel, BertModel
import pandas as pd
import numpy as np
from models import BertEncoder

import os
os.environ["TOKENIZERS_PARALLELISM"] = "false"

The current process just got forked. Disabling parallelism to avoid deadlocks...
To disable this warning, please explicitly set TOKENIZERS_PARALLELISM=(true | false)
The current process just got forked. Disabling parallelism to avoid deadlocks...
To disable this warning, please explicitly set TOKENIZERS_PARALLELISM=(true | false)


In [2]:
df_path='/home/ss4yd/vision_transformer/captioning_vision_transformer/prepared_prelim_data.csv'
tokenizer = AutoTokenizer.from_pretrained("emilyalsentzer/Bio_ClinicalBERT")
dataset = PreLoadedReps(df_path=df_path, tokenizer=tokenizer)
print(len(dataset))
# print(dataset[1])

1407


In [3]:
dataset[1][1]

(tensor([[  101,   123,  3423,   117,  8828, 22860,   120,  8828,  1106,  3597,
          12365, 15140,   102,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0]]),
 tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0]]),
 tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [4]:
text_encoder=BertEncoder()

tensor([[[ 1.7930, -0.0340,  2.7249,  ...,  0.0000,  0.0000,  0.0000],
         [ 3.2651,  3.6284,  0.6756,  ...,  0.0000,  0.0000,  0.0000],
         [-2.3195, -1.1073, -0.7593,  ...,  0.0000,  0.0000,  0.0000],
         ...,
         [-1.5459,  0.3128, -2.6518,  ...,  0.0000,  0.0000,  0.0000],
         [ 1.6841,  2.4295,  3.0448,  ...,  0.0000,  0.0000,  0.0000],
         [-2.4618,  1.4086, -2.0432,  ...,  0.0000,  0.0000,  0.0000]]],
       grad_fn=<PermuteBackward0>)